//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by R823_T.rc
//
#define IDCANCEL2                       3
#define ID_QUIT                         3
#define IDD_R823_T_DIALOG               102
#define IDD_R823_T_DIALOG_PREFERENCE    103
#define IDD_R823_T_DIALOG_SET           104
#define IDD_R823_T_DIALOG_QUERY         104
#define IDD_R823_T_DIALOG_EXPORT        105
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     129
#define IDB_BITMAP2                     130
#define IDI_ICON1                       136
#define IDD_DIALOG_NET                  137
#define IDC_BUTTON_BASIC_SETTING        1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_VOL_INQ              1002
#define ID_EXPORT                       1003
#define ID_VOL_DETAIL                   1004
#define IDC_TABLE_CONTENT               1010
#define IDC_TABLE_SUM                   1011
#define IDC_COMBO1                      1014
#define IDC_COMBO_RECORD                1014
#define IDC_COMBO2                      1015
#define IDC_COMBO_CONTENT               1015
#define IDC_RADIO2                      1016
#define IDC_RADIO3                      1017
#define IDC_PIC_LEFT                    1017
#define IDC_COMBO3                      1018
#define IDC_PIC_RIGHT                   1018
#define IDC_RADIO4                      1019
#define IDC_LIST1                       1019
#define IDC_LIST_CONTENT                1019
#define IDC_PROJECTNAME_INPUT           1020
#define IDC_PROJECT_STATIC              1021
#define IDC_SIZE_STATIC                 1022
#define IDC_SIZE_INPUT                  1023
#define IDC_ID_STATIC                   1024
#define IDC_IDENTIFICATION_INPUT        1025
#define IDC_VELOCITY_STATIC             1026
#define IDC_FREQUENCE_INPUT4            1027
#define IDC_VELOCITY_INPUT              1027
#define IDC_FREQUENCE_STATIC            1028
#define IDC_FREQUENCE_INPUT             1029
#define IDC_SENSIOR_STATIC              1030
#define IDC_SENSIOR_INPUT               1031
#define IDC_FILTER_STATIC               1032
#define IDC_FILTER_INPUT                1033
#define ID_SETTING_OK                   1034
#define ID_CANCEL                       1035
#define ID_SETTING_CANCEL               1035
#define IDC_FREQUENCE_STATIC_ITEM       1036
#define IDC_SENSIOR_STATIC_ITEM         1037
#define IDC_BROWSER                     1037
#define ID_EXPORT_OK                    1038
#define IDC_FILTER_STATIC_ITEM          1038
#define ID_EXPORT_FAILED                1039
#define IDC_PROJECT_STATIC_ITEM         1039
#define ID_QUERY_OK                     1040
#define IDC_SIZE_STATIC_ITEM            1040
#define ID_QUERY_FAILED                 1041
#define IDC_ID_STATIC_ITEM              1041
#define IDC_VELOCITY_STATIC_ITEM        1042
#define ID_BUTTON_EXPORT                1042
#define IDC_SETTING_GROUP               1043
#define IDC_EXPORT_GROUP                1044
#define IDC_STATIC_MID_DEFICIENCY       1044
#define IDC_PATH_STATIC                 1045
#define IDC_MID_DEFICIENCY_INPUT        1045
#define IDC_CHECK_SERIAL                1046
#define IDC_STATIC_MID_DEFICIENCY2      1046
#define IDC_CHECK_TINY                  1047
#define IDC_STATIC_SELECT               1047
#define IDC_MID_DEFICIENCY_INPUT2       1047
#define IDC_CHECK_MID                   1048
#define IDC_STATIC_RECORD               1048
#define IDC_STATIC_TINY_DEFICIENCY      1048
#define IDC_CHECK_HUGE                  1049
#define IDC_TINY_DEFICIENCY_INPUT       1049
#define IDC_STATIC_TEST_IND             1049
#define IDC_CHECK_RANGE                 1050
#define IDC_STATIC_HUGE_DEFICIENCY      1050
#define IDC_CHECK_VOL                   1051
#define IDC_HUGE_DEFICIENCY_INPUT       1051
#define IDC_STATIC_DISTANCE             1052
#define IDC_CHECK_IRON                  1052
#define IDC_DISTANCE_INPUT              1053
#define IDC_STATIC_TINY_DEFICIENCY2     1054
#define IDC_TINY_DEFICIENCY_INPUT2      1055
#define IDC_STATIC_TINY_DEFICIENCY3     1056
#define IDC_TINY_DEFICIENCY_INPUT3      1057
#define IDC_STATIC_MID_DEFICIENCY3      1058
#define IDC_MID_DEFICIENCY_INPUT3       1059
#define IDC_STATIC_HUGE_DEFICIENCY2     1060
#define IDC_HUGE_DEFICIENCY_INPUT2      1061
#define IDC_STATIC_HUGE_DEFICIENCY3     1062
#define IDC_HUGE_DEFICIENCY_INPUT3      1063
#define IDC_STATIC_GROUP_TINY           1064
#define IDC_STATIC_GROUP_MID            1065
#define IDC_STATIC_GROUP_HUGE           1066
#define IDC_STATIC_IRON_TRAMP1          1067
#define IDC_IRON_TRAMP_INPUT            1068
#define IDC_EDIT_ip                     1068
#define IDC_STATIC_GROUP_IRON_TRAMP     1069
#define IDC_EDIT_USERNAME               1069
#define IDC_STATIC_IRON_TRAMP2          1070
#define IDC_EDIT_PASSWORD               1070
#define IDC_IRON_TRAMP_INPUT2           1071
#define IDC_EDIT_FOLDER                 1071
#define IDC_STATIC_IRON_TRAMP3          1072
#define IDC_STATIC_IP                   1072
#define IDC_IRON_TRAMP_INPUT3           1073
#define IDC_STATIC_IP2                  1073
#define IDC_DISTANCE_STATIC_ITEM        1074
#define IDC_STATIC_IP3                  1074
#define IDC_STATIC_IP4                  1075
#define ID_NET_OK                       1076
#define ID_NET_CANCEL                   1077
#define IDC_BUTTON1                     1078
#define IDC_BUTTON_NET                  1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
